spring:
  application:
    name: flowfood
  datasource:
    url: jdbc:postgresql://localhost:5432/FlowFood
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: public

server:
  port: 8080